import { Router } from "express";
import { z } from "zod";
import { User } from "../models/User";
import { League } from "../models/League";
import { Season } from "../models/Season";
import { Team } from "../models/Team";
import { Match } from "../models/Match";
import { TipsterApplication } from "../models/TipsterApplication";
import { TipsterProfile } from "../models/TipsterProfile";
import { Prediction } from "../models/Prediction";
import { requireAuth, requireRole, type AuthRequest } from "../middleware/auth"; import { notify, notifyMany } from '../services/notificationService'; import { TipsterFollow } from '../models/TipsterFollow'; import { UserPick } from '../models/UserPick';

export const adminRouter = Router();
adminRouter.use(requireAuth, requireRole("admin"));
const id = z.string().regex(/^[a-f\d]{24}$/i, "Invalid MongoDB id");
const leagueBody = z.object({ externalId:z.string().optional(), name:z.string().min(1).max(120), country:z.string().min(1).max(100), logo:z.string().url().optional().or(z.literal("")), active:z.boolean().optional() });
const seasonBody = z.object({ leagueId:id, externalId:z.string().optional(), name:z.string().min(1).max(100), startDate:z.coerce.date().optional(), endDate:z.coerce.date().optional(), active:z.boolean().optional() });
const teamBody = z.object({ externalId:z.string().optional(), name:z.string().min(1).max(120), shortName:z.string().max(50).optional(), country:z.string().max(100).optional(), logo:z.string().url().optional().or(z.literal("")), active:z.boolean().optional() });
const matchBody = z.object({ externalId:z.string().optional(), leagueId:id, seasonId:id.optional(), homeTeamId:id, awayTeamId:id, kickoff:z.coerce.date(), status:z.enum(["scheduled","live","finished","postponed","cancelled"]).optional(), homeScore:z.number().int().min(0).optional(), awayScore:z.number().int().min(0).optional(), venue:z.object({name:z.string().max(150).optional(),city:z.string().max(100).optional()}).optional() });
const predictionBody = z.object({ tipsterId:id, matchId:id.optional().or(z.literal("")), fixture:z.string().min(1).max(200), league:z.string().max(120).optional().or(z.literal("")), prediction:z.string().min(1).max(200), odds:z.coerce.number().min(1), confidence:z.coerce.number().min(0).max(100).optional().or(z.literal("")), analysis:z.string().max(3000).optional().or(z.literal("")), status:z.enum(["pending","published","won","lost","void"]).optional(), profit:z.coerce.number().optional().or(z.literal("")) });

async function crud(model:any, body:any, req:any, res:any, next:any) { try { if(req.method==="GET"){const page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||25,1),100),search=typeof req.query.search==="string"?req.query.search.trim():"";const filter=search?{name:{$regex:search,$options:"i"}}:{};const [data,total]=await Promise.all([model.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit),model.countDocuments(filter)]);return res.json({data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});} const parsed=body.parse(req.body); if(req.method==="POST") return res.status(201).json({data:await model.create(parsed)}); const found=await model.findById(req.params.id); if(!found)return res.status(404).json({message:"Record not found"}); if(req.method==="PATCH"){Object.assign(found,parsed);await found.save();return res.json({data:found});} if(req.method==="DELETE"){await model.findByIdAndDelete(req.params.id);return res.json({ok:true});} } catch(e){next(e);} }
for(const [path,model,body] of [["leagues",League,leagueBody],["seasons",Season,seasonBody],["teams",Team,teamBody],["matches",Match,matchBody]] as const){ adminRouter.get(`/${path}`, (req,res,next)=>crud(model,body,req,res,next)); adminRouter.post(`/${path}`, (req,res,next)=>crud(model,body,req,res,next)); adminRouter.patch(`/${path}/:id`, (req,res,next)=>crud(model,body,req,res,next)); adminRouter.delete(`/${path}/:id`, (req,res,next)=>crud(model,body,req,res,next)); }

adminRouter.get("/dashboard", async (_req,res,next)=>{ try { const [users,leagues,seasons,teams,matches,live,finished,tipsterPending,tipsters,predictions,approved,rejected]=await Promise.all([User.countDocuments(),League.countDocuments(),Season.countDocuments(),Team.countDocuments(),Match.countDocuments(),Match.countDocuments({status:"live"}),Match.countDocuments({status:"finished"}),TipsterApplication.countDocuments({status:{ $in:["pending","under_review","more_info"]}}),TipsterProfile.countDocuments({active:true}),Prediction.countDocuments(),Prediction.countDocuments({status:"won"}),Prediction.countDocuments({status:"lost"})]); const totalSettled=approved+rejected; res.json({data:{users,leagues,seasons,teams,matches,live,finished,tipsterPending,tipsters,predictions,approvedPredictions:approved,lostPredictions:rejected,winRate:totalSettled?Math.round(approved/totalSettled*1000)/10:0}}); } catch(e){next(e);} });

adminRouter.get("/users", async (req,res)=>{ const page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||25,1),100),search=typeof req.query.search==="string"?req.query.search.trim():"",role=typeof req.query.role==="string"?req.query.role:undefined; const filter:any=search?{$or:[{name:{$regex:search,$options:"i"}},{email:{$regex:search,$options:"i"}}]}:{}; if(role) filter.role=role; const [data,total]=await Promise.all([User.find(filter).select("-passwordHash").sort({createdAt:-1}).skip((page-1)*limit).limit(limit),User.countDocuments(filter)]); res.json({data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}); });
adminRouter.patch("/users/:id", async(req,res)=>{ const body=z.object({name:z.string().min(2).max(100).optional(),role:z.enum(["user","admin","tipster"]).optional(),status:z.enum(["active","suspended"]).optional()}).parse(req.body); const user=await User.findByIdAndUpdate(req.params.id,{$set:body},{new:true}).select("-passwordHash"); if(!user)return res.status(404).json({message:"User not found"}); res.json({data:user}); });

adminRouter.get("/tipster-applications", async (req,res,next)=>{ try { const status=typeof req.query.status==="string"?req.query.status:undefined; const search=typeof req.query.search==="string"?req.query.search.trim():""; const filter:any={}; if(status) filter.status=status; if(search) filter.$or=[{username:{$regex:search,$options:"i"}},{bio:{$regex:search,$options:"i"}}]; const data=await TipsterApplication.find(filter).populate("userId","name email").populate("reviewedBy","name email").sort({createdAt:-1}).limit(200); res.json({data}); } catch(e){next(e);} });

adminRouter.get("/tipster-applications/:id", async(req,res)=>{ const item=await TipsterApplication.findById(req.params.id).populate("userId","name email"); if(!item)return res.status(404).json({message:"Application not found"}); res.json({data:item}); });

const reviewSchema=z.object({ action:z.enum(["under_review","approve","reject","more_info","suspend"]), adminNotes:z.string().max(3000).optional() });
adminRouter.patch("/tipster-applications/:id/review", async(req,res)=>{ const {action,adminNotes}=reviewSchema.parse(req.body); const application=await TipsterApplication.findById(req.params.id); if(!application)return res.status(404).json({message:"Application not found"}); const auth=req as AuthRequest; const now=new Date(); const map:any={under_review:"under_review",reject:"rejected",more_info:"more_info",suspend:"suspended",approve:"approved"}; application.status=map[action]; application.adminNotes=adminNotes; application.reviewedBy=auth.user!.id as any; application.reviewedAt=now; await application.save();
  if(action==="approve"){ const user=await User.findByIdAndUpdate(application.userId,{role:"tipster",status:"active"},{new:true}); if(!user)return res.status(404).json({message:"Applicant user not found"}); await TipsterProfile.findOneAndUpdate({userId:user._id},{userId:user._id,applicationId:application._id,username:application.username,bio:application.bio,country:application.country,expertise:application.expertise,profilePhoto:application.profilePhoto,socialLinks:application.socialLinks,active:true},{upsert:true,new:true,setDefaultsOnInsert:true}); }
  if(action==="suspend"){ await User.findByIdAndUpdate(application.userId,{status:"suspended"}); await TipsterProfile.findOneAndUpdate({userId:application.userId},{active:false}); }
  await notify(application.userId,{type:'tipster',title:`Tipster application ${application.status.replace('_',' ')}`,message: action==='approve' ? 'Your tipster application has been approved.' : action==='reject' ? 'Your tipster application was rejected.' : `Your application is now ${application.status.replace('_',' ')}.`,link:'/dashboard'}); res.json({data:application}); });

adminRouter.get("/tipsters", async(_req,res)=>{ const data=await TipsterProfile.find().populate("userId","name email status").sort({createdAt:-1}); res.json({data}); });
adminRouter.get("/predictions", async(req,res)=>{ const status=typeof req.query.status==="string"?req.query.status:undefined; const filter=status?{status}:{}; const data=await Prediction.find(filter).populate("tipsterId","name email").populate("matchId").sort({createdAt:-1}).limit(200); res.json({data}); });
function cleanPrediction(parsed:any){ const out:any={...parsed}; if(out.matchId==="") delete out.matchId; if(out.league==="") delete out.league; if(out.confidence==="") delete out.confidence; if(out.analysis==="") delete out.analysis; if(out.profit==="") delete out.profit; return out; }
adminRouter.post("/predictions", async(req,res,next)=>{ try { const parsed=cleanPrediction(predictionBody.parse(req.body)); const created=await Prediction.create(parsed); res.status(201).json({data:created}); } catch(e){next(e);} });
adminRouter.patch("/predictions/:id", async(req,res,next)=>{ try { const parsed=cleanPrediction(predictionBody.partial().parse(req.body)); const found=await Prediction.findById(req.params.id); if(!found) return res.status(404).json({message:"Prediction not found"}); Object.assign(found,parsed); if(parsed.status==="won"||parsed.status==="lost") found.resultAt=new Date(); if(parsed.status==="published"&&!found.publishedAt) { found.publishedAt=new Date(); const followers=await TipsterFollow.find({tipsterId:found.tipsterId}).select('userId'); await notifyMany(followers.map(x=>x.userId),{type:'follow',title:'New pick from a tipster you follow',message:`A new prediction is available: ${found.fixture}.`,link:'/picks'}); await notify(found.tipsterId,{type:'prediction',title:'Your prediction was published',message:`Your prediction for ${found.fixture} is now live.`,link:'/dashboard'}); } await found.save(); if(['won','lost','void'].includes(found.status)) { await settlePredictionRewards(String(found._id)); const pickStatus:any={won:'won',lost:'lost',void:'void'}; const picks=await UserPick.find({predictionId:found._id,status:'open'}); await UserPick.updateMany({predictionId:found._id,status:'open'},{$set:{status:pickStatus[found.status]}}); await notifyMany(picks.map(x=>x.userId),{type:'result',title:`Your pick is ${found.status}`,message:`${found.fixture}: ${found.prediction} was marked ${found.status}.`,link:'/dashboard'}); const followers=await TipsterFollow.find({tipsterId:found.tipsterId}).select('userId'); await notifyMany(followers.map(x=>x.userId),{type:'result',title:`Prediction ${found.status}`,message:`${found.fixture}: ${found.prediction} was marked ${found.status}.`,link:'/history'}); } res.json({data:found}); } catch(e){next(e);} });
adminRouter.delete("/predictions/:id", async(req,res)=>{ await Prediction.findByIdAndDelete(req.params.id); res.json({ok:true}); });
// --- Admin automation, rewards, AI picks and historical performance ---
import { SyncJob } from '../models/SyncJob';
import { RewardRule } from '../models/RewardRule';
import { RewardLedger } from '../models/RewardLedger';
import { BetOfDay } from '../models/BetOfDay';
import { settlePredictionRewards } from '../services/rewardService';
import { generateBetOfDay } from '../services/aiBetService';
import { runSync } from '../services/scheduler';

const rewardRuleBody=z.object({name:z.string().min(1).max(120),streak:z.coerce.number().int().min(1),amount:z.coerce.number().min(0),currency:z.string().min(1).max(10).default('GHS'),active:z.boolean().optional()});
adminRouter.get('/rewards/rules',async(_req,res,next)=>{try{res.json({data:await RewardRule.find().sort({streak:1})});}catch(e){next(e)}});
adminRouter.post('/rewards/rules',async(req,res,next)=>{try{res.status(201).json({data:await RewardRule.create(rewardRuleBody.parse(req.body))});}catch(e){next(e)}});
adminRouter.patch('/rewards/rules/:id',async(req,res,next)=>{try{const item=await RewardRule.findByIdAndUpdate(req.params.id,rewardRuleBody.partial().parse(req.body),{new:true});if(!item)return res.status(404).json({message:'Reward rule not found'});res.json({data:item});}catch(e){next(e)}});
adminRouter.delete('/rewards/rules/:id',async(req,res,next)=>{try{await RewardRule.findByIdAndDelete(req.params.id);res.json({ok:true});}catch(e){next(e)}});
adminRouter.get('/rewards/ledger',async(req,res,next)=>{try{const status=typeof req.query.status==='string'?req.query.status:undefined;const filter:any=status?{status}:{};const data=await RewardLedger.find(filter).populate({path:'tipsterId',populate:{path:'userId',select:'name email'}}).populate('predictionId','fixture prediction status resultAt').populate('ruleId','name streak amount currency').sort({createdAt:-1}).limit(500);const totals=await RewardLedger.aggregate([{$match:filter},{$group:{_id:'$status',amount:{$sum:'$amount'},count:{$sum:1}}}]);res.json({data,totals});}catch(e){next(e)}});
const rewardStatusBody=z.object({status:z.enum(['pending','approved','paid','cancelled']),note:z.string().max(500).optional()});
adminRouter.patch('/rewards/ledger/:id',async(req,res,next)=>{try{const item=await RewardLedger.findById(req.params.id);if(!item)return res.status(404).json({message:'Reward not found'});const b=rewardStatusBody.parse(req.body);item.status=b.status;item.note=b.note;if(b.status==='approved')item.approvedAt=new Date();if(b.status==='paid')item.paidAt=new Date();await item.save();const p=await TipsterProfile.findById(item.tipsterId);if(p){p.totalRewardsPaid=await RewardLedger.aggregate([{$match:{tipsterId:p._id,status:'paid'}},{$group:{_id:null,total:{$sum:'$amount'}}}]).then(x=>x[0]?.total||0);p.totalRewardsEarned=await RewardLedger.aggregate([{$match:{tipsterId:p._id,status:{$in:['pending','approved','paid']}}},{$group:{_id:null,total:{$sum:'$amount'}}}]).then(x=>x[0]?.total||0);await p.save();}res.json({data:item});}catch(e){next(e)}});
adminRouter.get('/rewards/summary',async(_req,res,next)=>{try{const [pending,approved,paid]=await Promise.all(['pending','approved','paid'].map(status=>RewardLedger.aggregate([{$match:{status}},{$group:{_id:null,amount:{$sum:'$amount'},count:{$sum:1}}}])));res.json({data:{pending:pending[0]||{amount:0,count:0},approved:approved[0]||{amount:0,count:0},paid:paid[0]||{amount:0,count:0}}});}catch(e){next(e)}});

adminRouter.get('/sync/status',async(_req,res,next)=>{try{const [latest,history]=await Promise.all([SyncJob.findOne().sort({startedAt:-1}),SyncJob.find().sort({startedAt:-1}).limit(30)]);res.json({data:{latest,history}});}catch(e){next(e)}});
adminRouter.post('/sync/run',async(req,res,next)=>{try{const type=req.body?.type==='live'?'live':'daily';const date=typeof req.body?.date==='string'?req.body.date:new Date().toISOString().slice(0,10);const job=await runSync(type,date);res.json({data:job});}catch(e){next(e)}});
adminRouter.post('/sync/run-daily',async(req,res,next)=>{try{const date=typeof req.body?.date==='string'?req.body.date:new Date().toISOString().slice(0,10);const job=await runSync('daily',date);const picks=await generateBetOfDay(date).catch(()=>[]);res.json({data:{job,picks}});}catch(e){next(e)}});

adminRouter.get('/prediction-history',async(req,res,next)=>{try{const page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||50,1),200);const status=typeof req.query.status==='string'?req.query.status:undefined;const tipsterId=typeof req.query.tipsterId==='string'?req.query.tipsterId:undefined;const filter:any={status:{$in:['won','lost','void']}};if(status)filter.status=status;if(tipsterId)filter.tipsterId=tipsterId;const [data,total,stats]=await Promise.all([Prediction.find(filter).populate('tipsterId','name email').populate('matchId').sort({resultAt:-1,createdAt:-1}).skip((page-1)*limit).limit(limit),Prediction.countDocuments(filter),Prediction.aggregate([{$match:filter},{$group:{_id:null,total:{$sum:1},wins:{$sum:{$cond:[{$eq:['$status','won']},1,0]}},profit:{$sum:{$ifNull:['$profit',0]}}}},{$project:{_id:0,total:1,wins:1,losses:{$subtract:['$total','$wins']},profit:1,winRate:{$cond:[{$gt:['$total',0]},{$multiply:[{$divide:['$wins','$total']},100]},0]}}}])]);res.json({data,pagination:{page,limit,total,pages:Math.ceil(total/limit)},stats:stats[0]||{total:0,wins:0,losses:0,profit:0,winRate:0}});}catch(e){next(e)}});

adminRouter.get('/bet-of-day',async(req,res,next)=>{try{const date=typeof req.query.date==='string'?req.query.date:new Date().toISOString().slice(0,10);const data=await BetOfDay.find({date}).populate({path:'matchId',populate:[{path:'homeTeamId',select:'name'},{path:'awayTeamId',select:'name'},{path:'leagueId',select:'name'}]}).sort({createdAt:1});res.json({data});}catch(e){next(e)}});
adminRouter.post('/bet-of-day/generate',async(req,res,next)=>{try{const date=typeof req.body?.date==='string'?req.body.date:new Date().toISOString().slice(0,10);res.json({data:await generateBetOfDay(date)});}catch(e){next(e)}});
const betStatus=z.object({status:z.enum(['draft','approved','published','won','lost','void']),prediction:z.string().min(1).optional(),confidence:z.coerce.number().min(0).max(100).optional(),risk:z.string().max(50).optional(),analysis:z.string().max(3000).optional()});
adminRouter.patch('/bet-of-day/:id',async(req,res,next)=>{try{const item=await BetOfDay.findByIdAndUpdate(req.params.id,betStatus.parse(req.body),{new:true});if(!item)return res.status(404).json({message:'Bet of the Day not found'});res.json({data:item});}catch(e){next(e)}});

// Seed sensible defaults once, without overwriting admin changes.
RewardRule.countDocuments().then(async count=>{if(count===0) await RewardRule.insertMany([{name:'3-win streak',streak:3,amount:50,currency:'GHS',active:true},{name:'5-win streak',streak:5,amount:150,currency:'GHS',active:true},{name:'10-win streak',streak:10,amount:500,currency:'GHS',active:true}]);}).catch(()=>undefined);
