import {Router} from 'express'; import {z} from 'zod'; import {requireAuth,requireRole,type AuthRequest} from '../middleware/auth'; import {Prediction} from '../models/Prediction'; import {TipsterProfile} from '../models/TipsterProfile'; import {UserPick} from '../models/UserPick'; import {Notification} from '../models/Notification'; import {TipsterFollow} from '../models/TipsterFollow'; import { getTipsterWallet, requestWithdrawal } from '../services/rewardService';
import { Subscription } from '../models/Subscription';
export const userRouter=Router(); userRouter.use(requireAuth);
userRouter.get('/picks',async(req:AuthRequest,res,next)=>{try{const data=await UserPick.find({userId:req.user!.id}).populate({path:'predictionId',populate:[{path:'tipsterId',select:'name'},{path:'matchId'}]}).sort({createdAt:-1}).limit(200);res.json({data})}catch(e){next(e)}});
userRouter.post('/picks',async(req:AuthRequest,res,next)=>{try{const b=z.object({predictionId:z.string().regex(/^[a-f\d]{24}$/i),stake:z.coerce.number().positive().max(100000)}).parse(req.body);const p=await Prediction.findOne({_id:b.predictionId,status:'published'});if(!p)return res.status(404).json({message:'Published prediction not found'});if(p.isPremium){const premium=await Subscription.exists({userId:req.user!.id,plan:'premium',status:{$in:['active','trialing']}});if(!premium)return res.status(403).json({message:'Premium subscription required for this prediction'});}const existing=await UserPick.findOne({userId:req.user!.id,predictionId:p._id,status:'open'});if(existing)return res.status(409).json({message:'This pick is already in your list'});const item=await UserPick.create({userId:req.user!.id,predictionId:p._id,stake:b.stake,potentialReturn:Math.round(b.stake*p.odds*100)/100});res.status(201).json({data:item})}catch(e){next(e)}});
userRouter.delete('/picks/:id',async(req:AuthRequest,res,next)=>{try{const item=await UserPick.findOneAndDelete({_id:req.params.id,userId:req.user!.id,status:'open'});if(!item)return res.status(404).json({message:'Pick not found'});res.json({ok:true})}catch(e){next(e)}});

userRouter.get('/notifications',async(req:AuthRequest,res,next)=>{try{const limit=Math.min(Math.max(Number(req.query.limit)||30,1),100);const data=await Notification.find({userId:req.user!.id}).sort({createdAt:-1}).limit(limit);const unread=await Notification.countDocuments({userId:req.user!.id,read:false});res.json({data,unread})}catch(e){next(e)}});
userRouter.patch('/notifications/:id/read',async(req:AuthRequest,res,next)=>{try{const item=await Notification.findOneAndUpdate({_id:req.params.id,userId:req.user!.id},{$set:{read:true}},{new:true});if(!item)return res.status(404).json({message:'Notification not found'});res.json({data:item})}catch(e){next(e)}});
userRouter.patch('/notifications/read-all',async(req:AuthRequest,res,next)=>{try{await Notification.updateMany({userId:req.user!.id,read:false},{$set:{read:true}});res.json({ok:true})}catch(e){next(e)}});
userRouter.get('/follows',async(req:AuthRequest,res,next)=>{try{const follows=await TipsterFollow.find({userId:req.user!.id}).populate('tipsterId','name email');res.json({data:follows})}catch(e){next(e)}});
userRouter.post('/follows/:tipsterId',async(req:AuthRequest,res,next)=>{try{const profile=await TipsterProfile.findOne({userId:req.params.tipsterId,active:true});if(!profile)return res.status(404).json({message:'Tipster not found'});if(String(profile.userId)===String(req.user!.id))return res.status(400).json({message:'You cannot follow yourself'});await TipsterFollow.create({userId:req.user!.id,tipsterId:profile.userId});res.status(201).json({ok:true})}catch(e:any){if(e?.code===11000)return res.status(409).json({message:'Already following this tipster'});next(e)}});
userRouter.delete('/follows/:tipsterId',async(req:AuthRequest,res,next)=>{try{await TipsterFollow.findOneAndDelete({userId:req.user!.id,tipsterId:req.params.tipsterId});res.json({ok:true})}catch(e){next(e)}});
userRouter.get('/tipster',async(req:AuthRequest,res,next)=>{try{if(req.user!.role!=='tipster')return res.status(403).json({message:'Tipster account required'});const profile=await TipsterProfile.findOne({userId:req.user!.id});const predictions=await Prediction.find({tipsterId:req.user!.id}).sort({createdAt:-1}).limit(100);res.json({data:{profile,predictions}})}catch(e){next(e)}});
userRouter.post('/tipster/predictions',requireRole('tipster'),async(req:AuthRequest,res,next)=>{try{const b=z.object({matchId:z.string().regex(/^[a-f\d]{24}$/i).optional(),fixture:z.string().min(3).max(200),league:z.string().max(120).optional(),prediction:z.string().min(2).max(200),odds:z.coerce.number().min(1),confidence:z.coerce.number().min(0).max(100).optional(),analysis:z.string().max(3000).optional()}).parse(req.body);const autoPremium=Number(b.odds)>=2 && Number(b.confidence||0)>=60; const p=await Prediction.create({...b,tipsterId:req.user!.id,isPremium:autoPremium,status:'pending',source:'tipster'});res.status(201).json({data:p,message:autoPremium?'Prediction submitted as a Premium candidate for admin review.':'Prediction submitted for admin review.'})}catch(e){next(e)}});


userRouter.get('/tipster/wallet',requireRole('tipster'),async(req:AuthRequest,res,next)=>{try{res.json({data:await getTipsterWallet(req.user!.id)});}catch(e){next(e)}});
userRouter.post('/tipster/wallet/withdraw',requireRole('tipster'),async(req:AuthRequest,res,next)=>{try{const b=z.object({amount:z.coerce.number().positive(),method:z.enum(['mobile_money','bank_transfer']),accountName:z.string().min(2).max(120),accountNumber:z.string().min(5).max(40),institution:z.string().min(2).max(120),note:z.string().max(500).optional()}).parse(req.body);res.status(201).json({data:await requestWithdrawal(req.user!.id,b.amount,b.method,{accountName:b.accountName,accountNumber:b.accountNumber,institution:b.institution},b.note),message:'Withdrawal request submitted for admin processing.'});}catch(e){next(e)}});
