import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import { env } from "./config/env";
import { authRouter } from "./routes/auth";
import { publicRouter } from "./routes/public";
import { adminRouter } from "./routes/admin";
import { analyticsRouter } from "./routes/analytics";
import { integrationsRouter } from "./routes/integrations";
import { providersRouter } from "./routes/providers";
import { userRouter } from "./routes/user";
import { errorHandler, notFound } from "./middleware/error";

export const app=express();
app.use(helmet());
app.use(cors({ origin: true, credentials: true }));
app.use(express.json({limit:"1mb"}));
app.use(cookieParser());
app.get("/api/v1/health",(_req,res)=>res.json({ok:true,service:"bratips-api",timestamp:new Date().toISOString()}));
app.use("/api/v1/auth",authRouter);
app.use("/api/v1",publicRouter);
app.use("/api/v1/admin",adminRouter);
app.use("/api/v1/me",userRouter);
app.use("/api/v1/admin/analytics", analyticsRouter);
app.use("/api/v1/admin/integrations", integrationsRouter);
app.use("/api/v1/admin/providers", providersRouter);
app.use(notFound);app.use(errorHandler);